feanil/initial maintenance
openedx/xblock-utils pull request #198
Opened 2023-05-08 21:56 UTC by feanil

- docs: Add an initial catalog-info.yaml file.
- docs: Update the README.rst file to include standard sections.

2023-05-15 14:45 UTC, feanil commented
The CI tests are failing on master and need a lot more work, I've confirmed that all the unit tests pass locally and created https://github.com/openedx/xblock-utils/issues/199 to follow up on fixing the CI.

2023-05-16 16:37 UTC, kdmccormick requested changes
Thanks for the cleanup!

2023-05-16 16:37 UTC, kdmccormick commented on README.rst
> +.. _Backstage: https://open-edx-backstage.herokuapp.com/catalog/default/component/xblock-utils
Why don't we use backstage.openedx.org as the canonical domain of Backstage? It would prevent this link from breaking if we ever move off of Heroku.

2023-05-16 16:37 UTC, kdmccormick commented on catalog-info.yaml
> +  description: "Various utilities for Xblocks"
```suggestion
  description: "Various utilities for XBlocks"
```

2023-05-16 19:09 UTC, kdmccormick commented on README.rst
> +  mkvirtualenv -p python3.8 xblock-utils
Nevermind, I realized that this is coming from the cookiecutter.

2023-05-17 15:06 UTC, kdmccormick commented on README.rst
> +  mkvirtualenv -p python3.8 xblock-utils
This feels assumptive, not prescriptive.

If the Open edX onboarding docs said "install virtualenvwrapper", then it'd be prescriptive.

2023-05-22 17:58 UTC, kdmccormick requested changes

2023-05-22 17:58 UTC, kdmccormick commented on README.rst
> +test base classes and documentation are useful for any XBlocks.
Needs rewording

2023-05-22 18:04 UTC, feanil commented on README.rst
> +test base classes and documentation are useful for any XBlocks.
pushed up some new wording.

2023-05-22 18:04 UTC, kdmccormick approved these changes
🎸

2023-05-22 18:04 UTC, kdmccormick commented on README.rst
> +documentation that are useful for any XBlocks.
```suggestion
These are a collection of utility functions, base test classes and
documentation that are useful for any XBlocks.
```

2023-05-22 18:14 UTC, merged